import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Card from '../../ui/Card';
const GettingStartedStep = ({ onComplete, onBack, }) => {
    const handleComplete = () => {
        localStorage.setItem('onboarding:completed', 'true');
        onComplete();
    };
    return (_jsx(Card, { variant: "highlight", padding: "lg", children: _jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "text-center space-y-2", children: [_jsx("h2", { className: "text-3xl font-bold", children: "You're All Set! \uD83C\uDF89" }), _jsx("p", { className: "text-muted-foreground", children: "Your Koinonia Connect account is ready to use" })] }), _jsxs("div", { className: "space-y-4 bg-muted/50 p-6 rounded-sm", children: [_jsx("h3", { className: "font-medium text-lg", children: "Next Steps:" }), _jsxs("ul", { className: "space-y-3", children: [_jsxs("li", { className: "flex gap-3", children: [_jsx("span", { className: "text-primary font-bold", children: "1." }), _jsxs("div", { children: [_jsx("p", { className: "font-medium", children: "Explore the Dashboard" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "View your communication analytics and metrics" })] })] }), _jsxs("li", { className: "flex gap-3", children: [_jsx("span", { className: "text-primary font-bold", children: "2." }), _jsxs("div", { children: [_jsx("p", { className: "font-medium", children: "Start a Conversation" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Send your first message to a team member" })] })] }), _jsxs("li", { className: "flex gap-3", children: [_jsx("span", { className: "text-primary font-bold", children: "3." }), _jsxs("div", { children: [_jsx("p", { className: "font-medium", children: "Customize Your Settings" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Adjust notifications and preferences anytime" })] })] }), _jsxs("li", { className: "flex gap-3", children: [_jsx("span", { className: "text-primary font-bold", children: "4." }), _jsxs("div", { children: [_jsx("p", { className: "font-medium", children: "Read Documentation" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Learn about all features and best practices" })] })] })] })] }), _jsx("div", { className: "bg-primary/10 border border-primary/20 p-4 rounded-sm", children: _jsxs("p", { className: "text-sm", children: [_jsx("span", { className: "font-medium", children: "Need help?" }), " Check out our", ' ', _jsx("a", { href: "#", className: "text-primary underline", children: "support center" }), ' ', "or contact our team anytime."] }) }), _jsxs("div", { className: "flex gap-3 pt-4", children: [_jsx("button", { type: "button", onClick: onBack, className: "flex-1 px-4 py-2.5 border border-border rounded-sm font-medium hover:bg-muted/50 transition-all", children: "Back" }), _jsx("button", { type: "button", onClick: handleComplete, className: "flex-1 bg-primary text-primary-foreground px-4 py-2.5 rounded-sm font-medium hover:opacity-90 transition-all", children: "Go to Dashboard" })] })] }) }));
};
GettingStartedStep.displayName = 'GettingStartedStep';
export default GettingStartedStep;
//# sourceMappingURL=GettingStartedStep.js.map