-- DEPRECATED: This migration is no longer needed
-- All necessary indices are already defined in the Prisma schema with @@index directives:
-- - ConversationMessage has @@index([direction, conversationId]) and @@index([createdAt])
-- - Member has @@index([createdAt])
-- - MessageRecipient has appropriate status indices
--
-- Prisma automatically creates these indices on schema changes.
-- This migration was attempting to create redundant indices and had errors
-- trying to reference columns that don't exist.
--
-- This migration is a no-op - all indices are handled by Prisma schema.
