import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Check, X } from 'lucide-react';
const comparisonFeatures = [
    {
        name: 'SMS Messaging',
        koinonia: true,
        twilio: true,
        pushpay: true,
        planningCenter: false,
        rightNow: true,
        breeze: true,
    },
    {
        name: 'Phone Encryption (E2E)',
        koinonia: true,
        twilio: false,
        pushpay: false,
        planningCenter: false,
        rightNow: false,
        breeze: false,
        unique: true,
    },
    {
        name: 'Message Templates',
        koinonia: true,
        twilio: false,
        pushpay: true,
        planningCenter: true,
        rightNow: true,
        breeze: true,
    },
    {
        name: 'Recurring Messages',
        koinonia: true,
        twilio: false,
        pushpay: true,
        planningCenter: true,
        rightNow: false,
        breeze: true,
    },
    {
        name: 'Multi-Location Support',
        koinonia: true,
        twilio: false,
        pushpay: true,
        planningCenter: true,
        rightNow: true,
        breeze: true,
    },
    {
        name: 'Two-Way Messaging',
        koinonia: true,
        twilio: true,
        pushpay: false,
        planningCenter: false,
        rightNow: false,
        breeze: false,
    },
    {
        name: 'Analytics Dashboard',
        koinonia: true,
        twilio: true,
        pushpay: true,
        planningCenter: true,
        rightNow: true,
        breeze: true,
    },
    {
        name: 'Member Management',
        koinonia: true,
        twilio: false,
        pushpay: true,
        planningCenter: true,
        rightNow: true,
        breeze: true,
    },
    {
        name: 'Group Segmentation',
        koinonia: true,
        twilio: false,
        pushpay: true,
        planningCenter: true,
        rightNow: true,
        breeze: true,
    },
    {
        name: 'API Access',
        koinonia: true,
        twilio: true,
        pushpay: false,
        planningCenter: false,
        rightNow: false,
        breeze: false,
    },
    {
        name: 'Security Logging',
        koinonia: true,
        twilio: false,
        pushpay: false,
        planningCenter: true,
        rightNow: false,
        breeze: false,
        unique: true,
    },
    {
        name: 'CSRF Protection',
        koinonia: true,
        twilio: false,
        pushpay: false,
        planningCenter: false,
        rightNow: false,
        breeze: false,
        unique: true,
    },
    {
        name: 'Mobile App',
        koinonia: true,
        twilio: false,
        pushpay: true,
        planningCenter: true,
        rightNow: true,
        breeze: true,
    },
    {
        name: '14-Day Free Trial',
        koinonia: true,
        twilio: false,
        pushpay: true,
        planningCenter: true,
        rightNow: false,
        breeze: true,
    },
    {
        name: 'Affordable Pricing',
        koinonia: true,
        twilio: true,
        pushpay: false,
        planningCenter: false,
        rightNow: false,
        breeze: false,
        unique: true,
    },
    {
        name: 'Church-Specific Design',
        koinonia: true,
        twilio: false,
        pushpay: true,
        planningCenter: true,
        rightNow: true,
        breeze: true,
    },
];
export default function Comparison() {
    return (_jsx("section", { id: "comparison", className: "relative py-20 px-4 sm:px-6 lg:px-8 bg-background overflow-hidden", children: _jsxs("div", { className: "max-w-7xl mx-auto", children: [_jsxs("div", { className: "text-center mb-16", children: [_jsx("h2", { className: "text-4xl font-bold text-foreground mb-6", children: "Why Choose Koinonia" }), _jsx("p", { className: "text-lg text-muted-foreground mb-4", children: "Comprehensive feature comparison with industry leaders" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "16 essential features for church communication across 6 platforms" })] }), _jsx("div", { className: "overflow-x-auto", children: _jsxs("div", { className: "bg-muted/20 rounded-lg border border-border/50 overflow-hidden min-w-full", children: [_jsxs("div", { className: "grid gap-3 p-4 border-b border-border/50 bg-gradient-to-r from-primary/5 to-transparent", style: { gridTemplateColumns: '200px repeat(6, 1fr)' }, children: [_jsx("div", { className: "font-semibold text-foreground", children: "Feature" }), _jsx("div", { className: "text-center", children: _jsx("div", { className: "font-semibold text-primary bg-primary/10 rounded px-2 py-1 inline-block", children: "Koinonia" }) }), _jsx("div", { className: "text-center text-xs font-semibold text-foreground", children: "Twilio" }), _jsx("div", { className: "text-center text-xs font-semibold text-foreground", children: "Pushpay" }), _jsx("div", { className: "text-center text-xs font-semibold text-foreground", children: "Planning Center" }), _jsx("div", { className: "text-center text-xs font-semibold text-foreground", children: "RightNow" }), _jsx("div", { className: "text-center text-xs font-semibold text-foreground", children: "Breeze" })] }), comparisonFeatures.map((feature, idx) => (_jsxs("div", { className: `grid gap-3 p-4 border-b border-border/30 hover:bg-primary/5 transition-colors ${feature.unique ? 'bg-primary/5' : idx % 2 === 0 ? 'bg-muted/10' : ''}`, style: { gridTemplateColumns: '200px repeat(6, 1fr)' }, children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "font-medium text-foreground", children: feature.name }), feature.unique && (_jsx("span", { className: "text-xs font-bold px-2 py-0.5 rounded-full bg-primary/20 text-primary", children: "Unique" }))] }), _jsx("div", { className: "flex justify-center", children: feature.koinonia ? (_jsx(Check, { className: "w-5 h-5 text-primary font-bold", strokeWidth: 3 })) : (_jsx(X, { className: "w-5 h-5 text-muted-foreground/20" })) }), _jsx("div", { className: "flex justify-center", children: feature.twilio ? (_jsx(Check, { className: "w-5 h-5 text-muted-foreground/50 font-bold", strokeWidth: 3 })) : (_jsx(X, { className: "w-5 h-5 text-muted-foreground/20" })) }), _jsx("div", { className: "flex justify-center", children: feature.pushpay ? (_jsx(Check, { className: "w-5 h-5 text-muted-foreground/50 font-bold", strokeWidth: 3 })) : (_jsx(X, { className: "w-5 h-5 text-muted-foreground/20" })) }), _jsx("div", { className: "flex justify-center", children: feature.planningCenter ? (_jsx(Check, { className: "w-5 h-5 text-muted-foreground/50 font-bold", strokeWidth: 3 })) : (_jsx(X, { className: "w-5 h-5 text-muted-foreground/20" })) }), _jsx("div", { className: "flex justify-center", children: feature.rightNow ? (_jsx(Check, { className: "w-5 h-5 text-muted-foreground/50 font-bold", strokeWidth: 3 })) : (_jsx(X, { className: "w-5 h-5 text-muted-foreground/20" })) }), _jsx("div", { className: "flex justify-center", children: feature.breeze ? (_jsx(Check, { className: "w-5 h-5 text-muted-foreground/50 font-bold", strokeWidth: 3 })) : (_jsx(X, { className: "w-5 h-5 text-muted-foreground/20" })) })] }, idx)))] }) }), _jsxs("div", { className: "mt-16 grid md:grid-cols-3 gap-6", children: [_jsxs("div", { className: "p-6 rounded-lg border border-border/50 bg-muted/20 hover:border-primary/30 transition-all", children: [_jsx("div", { className: "text-2xl mb-3", children: "\uD83D\uDD10" }), _jsx("h3", { className: "font-semibold text-foreground mb-2", children: "End-to-End Encryption" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Phone numbers encrypted with AES-256-GCM, searchable with HMAC-SHA256" })] }), _jsxs("div", { className: "p-6 rounded-lg border border-border/50 bg-muted/20 hover:border-primary/30 transition-all", children: [_jsx("div", { className: "text-2xl mb-3", children: "\uD83D\uDEE1\uFE0F" }), _jsx("h3", { className: "font-semibold text-foreground mb-2", children: "Enterprise Security" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "CSRF protection, rate limiting, security event logging, full audit trails" })] }), _jsxs("div", { className: "p-6 rounded-lg border border-border/50 bg-muted/20 hover:border-primary/30 transition-all", children: [_jsx("div", { className: "text-2xl mb-3", children: "\u26EA" }), _jsx("h3", { className: "font-semibold text-foreground mb-2", children: "Church-First Design" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Built specifically for churches with affordable pricing and 14-day free trial" })] })] }), _jsx("div", { className: "mt-12 text-center", children: _jsxs("div", { className: "inline-flex items-center gap-8 text-sm", children: [_jsxs("div", { children: [_jsx("div", { className: "text-2xl font-bold text-primary", children: "16" }), _jsx("div", { className: "text-muted-foreground", children: "Features Compared" })] }), _jsxs("div", { children: [_jsx("div", { className: "text-2xl font-bold text-primary", children: "6" }), _jsx("div", { className: "text-muted-foreground", children: "Platforms" })] }), _jsxs("div", { children: [_jsx("div", { className: "text-2xl font-bold text-primary", children: "3" }), _jsx("div", { className: "text-muted-foreground", children: "Unique to Koinonia" })] })] }) })] }) }));
}
//# sourceMappingURL=Comparison.js.map